
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/itheima353?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: provider-service

mybatis:

  type-aliases-package: com.itheima.dao

  mapper-locations: classpath:mapper/*Mapper.xml
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
personName: 蔡旭坤
